### ISSUE TITLE
Infer relative usage: IndexError: list index out of range

### ISSUE THREAD

**Issue by peterkilfeather** [zavolanlab/PAQR_KAPAC#12] opened 2019-11-21 14:50 UTC
Hi, I am running the example data through the snakemake pipeline to test it. Part one proceeds successfully, however I get a 'list index out of range' error while it runs the 'deNovo-used-sites-and-usage-inference.single_distal_included.py' script. I have attached the log.

I am using a conda installation, using the 'UPDATED' requirements text file. 
I have attached the log from the failing step.

Thanks,
Peter
[infer_relative_usage.log](https://github.com/zavolanlab/PAQR_KAPAC/files/3875216/infer_relative_usage.log)

**Comment by peterkilfeather** [comment] 2019-11-22 06:53
I have since changed the number of cores to below my max (<8) and now get the [end_idx error](https://github.com/zavolanlab/PAQR_KAPAC/issues/9)

**Comment by koljaLanger** [comment] 2019-11-27 09:22
I tested the script with an input for --processor that is far beyond the available number of cores but could not reproduce the error.
Also since this thread refers now to the [end_idx error](https://github.com/zavolanlab/PAQR_KAPAC/issues/9) I close it for now. 
Please feel free to reopen it if the problem persists.

**Closed as completed by koljaLanger** 2019-11-27 09:22 UTC
