### ISSUE TITLE
Missing conda packages break creation of py2_paqr environment.

### ISSUE THREAD

**Issue by ClarinetK622** [zavolanlab/PAQR_KAPAC#20] opened 2020-10-23 20:53 UTC
Hi there, 

Python 2.7.11 does not seem to be available to install via the 'conda install python=2.7.11' step in the py2-paqr virtual environment creation. Additionally, pymongo 3.4.0 does not seem to be available either. Perhaps this is an issue with my installation in particular; however, checking for these versions with 'conda search --full-name python' and 'conda search --full-name pymongo' seems to show they are missing from the default repos. It may be a similar issue to the one you encountered early on with the python3 environment. If this is the case, it would be best to update the installation readme to reflect the changes in availability of these components.

Much thanks!

**Comment by koljaLanger** [comment] 2020-11-04 16:37
Hi
Many thanks for pointing out this problem! We are currently working on a solution. The problem is not 100% reproducible and is presumably a direct consequence of anaconda to [remove the "free" channel](https://www.anaconda.com/blog/why-we-removed-the-free-channel-in-conda-4-7). Once we found a reasonable solution, we'll post it here!

Ralf

**Comment by koljaLanger** [comment] 2020-11-11 07:04
Hi
We updated the repo and the README instructions to create the python2 conda environment. The python2 environment can now be created again with the command in the README file (using the updated version of the requirements file).

I consider this issue as solved and will close it now but feel free to reopen it at any time if you encounter any problem!

**Closed as completed by koljaLanger** 2020-11-11 07:04 UTC
